# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd25bd0cb062cef03e1e4c9f3f8033b6e3d2c179be2ea6743bc5fcb309e543cb1470bb4bc3ee8841dd208e719e3e40d1704e94f184e12698cbc1c6b18a8e90bd

test:
  secret_key_base: 08b24e0c9f3237fa8f3bc0fb1eec793b299798f840fbddc16688523835656b80c21e4f74ceacc9b7993264937040f12da23cf0fbcad90c6d0cd249161bb952c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
